apiVersion: batch/v1
kind: CronJob
metadata:
  name: notif-service
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: notif-service
        spec:
          serviceAccountName: notif-sa
          restartPolicy: Never
          containers:
            - name: notif
              image: YOUR_DOCKERHUB/library-notification-service:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: notif-config
                - secretRef:
                    name: notif-smtp-secret
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                seccompProfile:
                  type: RuntimeDefault
