name: Build docker image

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        registry: docker.io
        repository: quentindethy/notification-service
        tag_with_sha: true
    - name: Build and Run Tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v1
        - name: Build and Run Tests
          run: # execute your tests generating test results
        -  name: Publish Test Report
          uses: mikepenz/action-junit-report@v2
          if: always() # always run even if the previous step fails
          with:
            report_paths: '**/junit-reports/TEST-*.xml'
